In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4], dtype=np.float)
print(x)

[ 1.  2.  3.  4.]


In [3]:
y = 2.0 * x + 1.0
print(y)

[ 3.  5.  7.  9.]


In [4]:
y = np.array([1,1,1,1], dtype=np.float)
z = x + 2 * y
print(z)

[ 3.  4.  5.  6.]


In [5]:
print("平均 : ", np.mean(x))
print("分散 : ", np.var(x))
print("最大 : ", np.max(x))

平均 :  2.5
分散 :  1.25
最大 :  4.0


In [6]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10, 11, 12]], dtype=np.float)
print(A)

[[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]
 [ 10.  11.  12.]]


In [8]:
print(A.shape)

(4, 3)


In [9]:
B = 2 * A + 1
print(B)

[[  3.   5.   7.]
 [  9.  11.  13.]
 [ 15.  17.  19.]
 [ 21.  23.  25.]]


In [10]:
print("全集計 : ", np.max(A))
print("列集計 : ", np.max(A, axis=0))
print("行集計 : ", np.max(A, axis=1))

全集計 :  12.0
列集計 :  [ 10.  11.  12.]
行集計 :  [  3.   6.   9.  12.]


In [11]:
A = np.array([[1,2,3],
              [4,5,6]], dtype=np.float)
B = np.array([[0,1,2],
              [2,3,4]], dtype=np.float)
print(A + B)

[[  1.   3.   5.]
 [  6.   8.  10.]]


In [12]:
C = np.array([[0,1],
              [2,3]], dtype=np.float)
print(A + C)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [13]:
import pandas as pd
d = pd.DataFrame({
        "a" : [1, 2, 3],
        "x" : [1.0, -1.5, 2.5],
        "label" : ["l1", "l2", "l3"]
})

In [14]:
print(d["a"])

0    1
1    2
2    3
Name: a, dtype: int64


In [15]:
print(d[["a", "x", "label"]])

   a    x label
0  1  1.0    l1
1  2 -1.5    l2
2  3  2.5    l3


In [16]:
d["new_col"] = [10, 100, 1000]
print(d)

   a label    x  new_col
0  1    l1  1.0       10
1  2    l2 -1.5      100
2  3    l3  2.5     1000


In [17]:
print("mean of a = ", d["a"].mean())
print("std of x = ", d["x"].std())

mean of a =  2.0
std of x =  2.0207259421636903
